[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_31"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.31"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/12/artifacts/kubernetes/v1.31.4/kubernetes-src.tar.gz"
sha512 = "822cb865536757b1e62e3799a36dc2e2bde914aedef7a4e8179946a363a5bfd415d0c5a0f4c1ad031266b429cea2faff5fa75f12f63ac13cb25525b40ecd1dd4"

[build-dependencies]
glibc = { path = "../glibc" }
