[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_31"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.31"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/9/artifacts/kubernetes/v1.31.3/kubernetes-src.tar.gz"
sha512 = "c383516d9661ef5545dbd88194b805e913571bd78b709373b4601dd15d95020812d14eea33836a692fdb14a4c1d7be0b328723e4f8adcfc4685649c4ccecfa14"

[build-dependencies]
glibc = { path = "../glibc" }
