[package]
name = "netdog"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
source-groups = [
    "netdog",
    "dogtag",
]

[build-dependencies]
glibc = { path = "../glibc" }
