[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_30"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.30"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-30/releases/23/artifacts/kubernetes/v1.30.8/kubernetes-src.tar.gz"
sha512 = "06d308d962354ab763871a613fcbc83992b1e84482a90a7a0a7c218cd19c80471095c204dd416c8947547a0faf4ec3f0490bfef12ec663abc6db5af0727d9a9b"

[build-dependencies]
glibc = { path = "../glibc" }
