[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_32"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.32"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-32/releases/3/artifacts/kubernetes/v1.32.0/kubernetes-src.tar.gz"
sha512 = "dd3907b28a10686b63b8aeba88b2ee9d79a1f42546a2f57b3e5a8c837ea186e807d70822fa65c3fc4f36d57209365a204c4d4a7e3eddf4191c45abfde592bc44"

[build-dependencies]
glibc = { path = "../glibc" }
