[package]
name = "nvme-cli"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-nvme/nvme-cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-nvme/nvme-cli/archive/v2.11/nvme-cli-2.11.tar.gz"
sha512 = "33de20ad990a3b87fef46fa486832edde41907223aa6b8a47606e605b360745fd7e2054226bf93a59b2a09c6bc04d0b684e4b3bb27c3fc0e6110c64a558cadc0"

[build-dependencies]
glibc = { path = "../glibc" }
libjson-c = { path = "../libjson-c" }
libnvme = { path = "../libnvme" }
