[package]
name = "aws-iam-authenticator"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes-sigs/aws-iam-authenticator/archive/v0.6.29/aws-iam-authenticator-0.6.29.tar.gz"
sha512 = "276efbbf44228b7ef6fe45e80c19443b134664d940706f2634e7478c4e8a3d2499bd0cbe70e1b7916af47dbc66ca1b5419f4738ad1f94ef82fe88f3a06f27d65"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
