[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_29"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.29"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/27/artifacts/kubernetes/v1.29.11/kubernetes-src.tar.gz"
sha512 = "c06e7b45164363ed18667222d8cabbfc07c346cfd7243b3ff49ac7b3b47ca9ce5630d33eb6d1823dc70579a5cff0378dcd9a1c7078b66217f6e2a4d4c4d909f6"

[build-dependencies]
glibc = { path = "../glibc" }
