[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_29"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.29"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/kubernetes/v1.29.9/kubernetes-src.tar.gz"
sha512 = "5b0d50c6779feb5f2b06a15cc5962e69d97d1554bcc456171ef3780699529c1a28357e82d22614fb48941dc450e6150d1a3c41dfe1be27d4c38894c99cc5e656"

[build-dependencies]
glibc = { path = "../glibc" }
