[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "ecr-credential-provider-1_29"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "ecr-credential-provider-1.29"
releases-url = "https://github.com/kubernetes/cloud-provider-aws/releases"

[[package.metadata.build-package.external-files]]
url = "https://codeload.github.com/kubernetes/cloud-provider-aws/tar.gz/v1.29.7"
path = "cloud-provider-aws-1.29.7.tar.gz"
sha512 = "e4cedb1adfaac2ab3c82817ce2ec3b1c4a6c50a456ba01b032baac4cebad94d804adafbf09d7bea5550c3dadf6576313d81bae6b522f42d71e37c1f4ce7a2c08"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
