[package]
name = "kmod"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.kernel.org/pub/linux/utils/kernel/kmod"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-33.tar.xz"
sha512 = "32d79d0bb7e89012f18458d4e88325f8e19a7dba6e1d5cff01aec3e618d1757b0f7c119735bf38d02e0d056a14273fd7522fca7c61a4d12a3ea5854bb662fff8"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
libzstd = { path = "../libzstd" }
