[package]
name = "libnetfilter_conntrack"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnetfilter_conntrack/files"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_conntrack/files/libnetfilter_conntrack-1.1.0.tar.xz"
sha512 = "5435f45b61e4e13b63b4a39f0c34fb0b59d2eed1e5dc182bc91369b72df54f5a555c111223f4f4a786a2c47dd5c6efd97205b8dca2f522e28d9d54035f928882"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_conntrack/files/libnetfilter_conntrack-1.1.0.tar.xz.sig"
sha512 = "b3125d49976d2475e942f74bb3e57632b6643af6f65ea394a71d091759723d4f1220c6cd6116a7820e2c91069883898ad84e9c77355328e71b47906db8501cbe"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnfnetlink = { path = "../libnfnetlink" }
