[package]
name = "iproute"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "http://kernel.org/pub/linux/utils/net/iproute2"

[[package.metadata.build-package.external-files]]
url = "https://kernel.org/pub/linux/utils/net/iproute2/iproute2-6.9.0.tar.xz"
sha512 = "1cbb234cb8f94213c3529f0b74fed5a575ff1fb838e783b8d2b440643c2e91246eda42e9b26e9775897aadb8b8133d199b2851b8ea0df06a899dc02acf403325"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libmnl = { path = "../libmnl" }
libselinux = { path = "../libselinux" }
