[package]
name = "binutils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.kernel.org/gnu/binutils/binutils-2.41.tar.xz"
sha512 = "5df45d0bd6ddabdce4f35878c041e46a92deef01e7dea5facc97fd65cc06b59abc6fba0eb454b68e571c7e14038dc823fe7f2263843e6e627b7444eaf0fe9374"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
