[package]
name = "libbpf"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/libbpf/libbpf/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/libbpf/libbpf/archive/refs/tags/v1.4.5.tar.gz"
sha512 = "c5ed459e89a8897ef7c892723c61efb2f2fdb0e7bea63eaff1c9936d368d2cc9e63b8c093207eef0df3109c021156c52ddb570757f69c54e713909e866dbb2f5"

[build-dependencies]
glibc = { path = "../glibc" }
libelf = { path = "../libelf" }
libz = { path = "../libz" }
