[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# ECS agent
[package.metadata.build-package]
releases-url = "https://github.com/aws/amazon-ecs-agent/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.89.2/amazon-ecs-agent-1.89.2.tar.gz"
sha512 = "024f30daa6192f6e03771e507d776d01ec2c86b6cd7682e3b62d5f0e3e1b017b56360ca8e088ea183a4d04e104dc6e2e572ad9658d4bfcdab166d579a3ee1bc8"

[build-dependencies]
glibc = { path = "../glibc" }
