[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# ECS agent
[package.metadata.build-package]
releases-url = "https://github.com/aws/amazon-ecs-agent/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.88.0/amazon-ecs-agent-1.88.0.tar.gz"
sha512 = "1d7f38cae0fb7401b48feca4d6ecb270c5c5a5efc4367c58ff8384d2175b4c0b6a76bbe350ab231108eec542a3d6f0d9b8ac60dc121d5fee9a86ef812fdf9785"

[build-dependencies]
glibc = { path = "../glibc" }
