[package]
name = "libnfnetlink"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "http://netfilter.org/projects/libnfnetlink/files"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnfnetlink/files/libnfnetlink-1.0.2.tar.bz2"
sha512 = "a5e9ae22831f1d17703f83953f3b0ef898e8b3fa7f0f771b038db51816ddae3158574380ac4d45c09fb8fbb8677e2ccdcc5c4736e3b09de06eac99f899130854"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnfnetlink/files/libnfnetlink-1.0.2.tar.bz2.sig"
sha512 = "3dcb980fb209c9faa9774f0393bc3b4b5fa6e899330f0d0dcb92307984f696b869de27c22dd54d7f181bddd72e104b38e8617af6bb3d6fe992a96da172b10457"

[build-dependencies]
glibc = { path = "../glibc" }
