[package]
name = "nvidia-k8s-device-plugin"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/k8s-device-plugin/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/k8s-device-plugin/archive/v0.17.0/v0.17.0.tar.gz"
path = "k8s-device-plugin-0.17.0.tar.gz"
sha512 = "912d324d22bc18994319d4188a3d859e5af58ec6bd7da01f632a210dbb313b6ac8d5105e4558f03b49ed56005383eca6c25f215c24ca7b981b60cd0c510516ed"

[build-dependencies]
glibc = { path = "../glibc" }
