[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/besser82/libxcrypt/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz"
sha512 = "468560e6f90877540d22e32c867cbcf3786983a6fdae6ef86454f4b7f2bbaae1b6589d1af75cda73078fa8f6e91b1a32f8353f26d433246eef7be3e96d4ae1c7"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz.asc"
sha512 = "5fdf9a48d0de4c6394122845b9e0c5eecb65b0a7fea9b48c30cb69ec6eb0d0f0e9f4711c6d9d8d8a6c86bd56e0a4e3997acabebce03c618475884bf9d6998657"

[build-dependencies]
glibc = { path = "../glibc" }
