[package]
name = "libexpat"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/libexpat/libexpat/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.xz"
sha512 = "620da34d98524478b445038bf1dd439790fe11169496516425fca922226797835c27549fc5fb825792b516563b24eb922d9ad8f27d20a0229e7ee8cd640dfb25"

[[package.metadata.build-package.external-files]]
url = "https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.xz.asc"
sha512 = "e81764d4afb9b4e277b3f67921255c8415ffb37320939c847a17c94be12917bca5f4c6c14225b1e68594811f154e5e931761538c5aac6eb9b4bf360339753512"

[build-dependencies]
glibc = { path = "../glibc" }
