[package]
name = "libjson-c"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/json-c/json-c/tags"

[[package.metadata.build-package.external-files]]
url = "https://github.com/json-c/json-c/archive/refs/tags/json-c-0.18-20240915.tar.gz"
path = "json-c-0.18-20240915.tar.gz"
sha512 = "219d8c0da9a4016b74af238cc15dbec1f369a07de160bcc548d80279028e1b5d8d928deb13fec09c96a085fc0ecf10090e309cbe72d0081aca864433c4ae01db"

[build-dependencies]
glibc = { path = "../glibc" }
