[package]
name = "runc"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/opencontainers/runc/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/opencontainers/runc/releases/download/v1.1.15/runc.tar.xz"
path = "runc-v1.1.15.tar.xz"
sha512 = "55282eb699565ba77e7db883a89c005d4663cfa1270534a0bd383db9935f0477e9406fe0c689bad4f93b39b7f1c9915559a1bf9bf52b38eea51028d1d3eb0887"

[[package.metadata.build-package.external-files]]
url = "https://github.com/opencontainers/runc/releases/download/v1.1.15/runc.tar.xz.asc"
path = "runc-v1.1.15.tar.xz.asc"
sha512 = "01c259efa90d1ba73dee09251d942bd8936a470b24151eb56149a0aa864cc7e7ff53a7e085e1e617423040354d8c60729147231efe1e9e8ac77da605c465f783"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
