[package]
name = "libnl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/thom311/libnl/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-3.11.0.tar.gz"
sha512 = "69ecec6e792fc7b9c443fff8742cf45782af5c5c4664687440942eaeb616ba7b4ed2b606e33c5d86e44e6b49a9c79a1fed4b7c77781a059e13cf6a844d94530e"

[[package.metadata.build-package.external-files]]
url = "https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-3.11.0.tar.gz.sig"
sha512 = "de98fdd254ec587c1e467b590b6f876c8dee0ef10be86b0644c6de366f4deba9205ffa1881d6a6c394af9543dea38eb4553139ad9293c5788ef23c15db4381df"

[build-dependencies]
glibc = { path = "../glibc" }
