[package]
name = "host-ctr"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
source-groups = [ "host-ctr" ]

[lib]
path = "../packages.rs"

[build-dependencies]
glibc = { path = "../glibc" }
