[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_28"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.28"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-28/releases/35/artifacts/kubernetes/v1.28.14/kubernetes-src.tar.gz"
sha512 = "171a3d8875706d43a753cb03039fa6cffc6e9f7422bad3dbc558e41bf997b6cbdb85859eadad13e31dbabac6e032024d6b697c96f8671bc7b8875b76cf193b81"

[build-dependencies]
glibc = { path = "../glibc" }
