[package]
name = "chrony"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://chrony-project.org/releases/"

[[package.metadata.build-package.external-files]]
url = "https://chrony-project.org/releases/chrony-4.6.1.tar.gz"
sha512 = "646ae08f2587366236796f2399d8ab3eb570979e0d82f5d13f5cec49939054c876cc93dc20c8d38e105fd3500e1720d05a223a15076783cd882d0de43afd9c7e"

[[package.metadata.build-package.external-files]]
url = "https://chrony-project.org/releases/chrony-4.6.1-tar-gz-asc.txt"
sha512 = "992b706636bf3a7eb6d502562a4990c9d8e20e5f3011d2cdb2ceb32220e9a1c2bfa6eca767212cee49b811823872602dc33f9e7201a7f9a93cc9c90e81b1db49"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libncurses = { path = "../libncurses" }
readline = { path = "../readline" }
