[package]
name = "amazon-ecs-cni-plugins"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
# Use the Git submodule commit from aws/amazon-ecs-agent rather than an upstream release.
releases-url = "https://github.com/aws/amazon-ecs-agent/commits/master/amazon-ecs-cni-plugins"

[[package.metadata.build-package.external-files]]
# This is locked against the version shipped in ecs-agent
# Verify that the ecs-agent version shipped in bottlerocket tracks the same one here
# https://github.com/aws/amazon-ecs-agent/releases
url = "https://github.com/aws/amazon-ecs-cni-plugins/archive/7b4ec6016ab221469fa3abfc00ea7c05f236c26c/amazon-ecs-cni-plugins.tar.gz"
sha512 = "234021e1132a8c7101603f26c2b4d18e2a54dd8d6e879ae5138fcafac012f792dc25ab1bad37bde5d4e299b996340de557dbe9ba928eae2a8565adff5bd481a8"

[build-dependencies]
glibc = { path = "../glibc" }
