[package]
name = "login"
version = "0.0.1"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]

[lib]
path = "../packages.rs"

[build-dependencies]
glibc = { path = "../glibc" }
