[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "ecr-credential-provider-1_27"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "ecr-credential-provider-1.27"
releases-url = "https://github.com/kubernetes/cloud-provider-aws/releases"

[[package.metadata.build-package.external-files]]
url = "https://codeload.github.com/kubernetes/cloud-provider-aws/tar.gz/v1.27.10"
path = "cloud-provider-aws-1.27.10.tar.gz"
sha512 = "e173d4504dd0912530cf5db6d16319df62e06a7f982f835f8a69bd86501179cba78926f3fa6406da926424eab02cb4610f63c9d22ce6ed83fb43203c3ae0cb6b"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
