[package]
name = "liburcu"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://lttng.org/files/urcu"

[[package.metadata.build-package.external-files]]
url = "https://lttng.org/files/urcu/userspace-rcu-0.14.1.tar.bz2"
sha512 = "46137525854164df05326202909689b62f8f3aa6e04127eb9157a83aed8180f35a68332ec66e4e4fc9b0c046b64c64b492caed4b64f86f87a31579e4209ec345"

[[package.metadata.build-package.external-files]]
url = "https://lttng.org/files/urcu/userspace-rcu-0.14.1.tar.bz2.asc"
sha512 = "8797b7ae063cbee339fd65e25866e2e2fab91d1dd39389a811875550d9dcf3f6eac7a582c40dce553caccc14230f44c26bb6ba79bbfadf7e56dac4827d20acbd"

[build-dependencies]
glibc = { path = "../glibc" }
