[package]
name = "iptables"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.netfilter.org/projects/iptables/files"

[[package.metadata.build-package.external-files]]
url = "https://www.netfilter.org/projects/iptables/files/iptables-1.8.11.tar.xz"
sha512 = "4937020bf52d57a45b76e1eba125214a2f4531de52ff1d15185faeef8bea0cd90eb77f99f81baa573944aa122f350a7198cef41d70594e1b65514784addbcc40"

[[package.metadata.build-package.external-files]]
url = "https://www.netfilter.org/projects/iptables/files/iptables-1.8.11.tar.xz.sig"
sha512 = "8bde9436b6c6c9d97d9b1cadc417035c209e39b49111ea08fe35b714bbf94721ad0b8b2870791d3bf98154f64912109c6bdeb0ee33f954d0d3a8c3582a97f3f2"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnetfilter_conntrack = { path = "../libnetfilter_conntrack" }
libnfnetlink = { path = "../libnfnetlink" }
libnftnl = { path = "../libnftnl" }
