[package]
name = "aws-signing-helper"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/aws/rolesanywhere-credential-helper/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/rolesanywhere-credential-helper/archive/v1.4.0/rolesanywhere-credential-helper-v1.4.0.tar.gz"
sha512 = "6da4911c89ea24a1356964f5cedc2cdb06c927a930b189efbf5ccaae60e582714b264fb787b2ed9d575ce5e588d1a057d7f311022c459aca7b7afd9f9c2bc801"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
