[package]
name = "libsemanage"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/SELinuxProject/selinux/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/3.7/libsemanage-3.7.tar.gz"
sha512 = "4b6370b02116364964ff24b93fb6629c885611de78419f649a027db38b4f1c3b3adf3b438efb34a92b49407ab8f9446ed4091fe4c99fa4752f0f5e3e31589415"

[build-dependencies]
glibc = { path = "../glibc" }
libaudit = { path = "../libaudit" }
libselinux = { path = "../libselinux" }
libsepol = { path = "../libsepol" }
