[package]
name = "findutils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/pub/gnu/findutils"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/pub/gnu/findutils/findutils-4.10.0.tar.xz"
sha512 = "b8b683d21cd26c6da4f41c56e83cadbda4780f8610a2bbd4b4e34bb1f339c3209721974b03e076d5eef0331fd876d947b398197aad37c29bbcc2e0405c641b34"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/pub/gnu/findutils/findutils-4.10.0.tar.xz.sig"
sha512 = "a835153a0671309021be187bf78afee58d9682acb40545aaa9dd187f0ebdea0cfa5583bd03f363243633ea056ddb0a7a6603987ab5e34a608426cb4265ac6d8f"

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
