[package]
name = "libnvme"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-nvme/libnvme/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-nvme/libnvme/archive/v1.11/libnvme-1.11.tar.gz"
sha512 = "5c1d00fe57ff699be01c326e24612da25e1772578928e2c70fb5f67e8a9fe0fa4c95e18f58d4abefa0e163e99c9e37b1109298e805e174b033e749d19865336b"

[build-dependencies]
glibc = { path = "../glibc" }
