[package]
name = "cni-plugins"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containernetworking/plugins/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containernetworking/plugins/archive/v1.6.1/plugins-1.6.1.tar.gz"
sha512 = "62b4e2c5c4bf6a9b21880e7b145547bec153f591926419d9960345cc7fb7d499ae44b0236928bbfeb46e383f38018d7504e58da1dd8a6ad39ef4ae3122b3be56"

[build-dependencies]
glibc = { path = "../glibc" }
