[package]
name = "libnetfilter_cthelper"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnetfilter_cthelper/files"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.1.tar.bz2"
sha512 = "f0591edd579aee92b62446e2b8fef6af9c404848c42c8da76850bb01aec3567442612f53cf8d3af6ba4d6d920487bff310a4e547bccf595478b1f96b4280eada"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.1.tar.bz2.sig"
sha512 = "991f1e20673eb290fc9b4b35c5dd0c27223398e560f4807b5497fc6b69780594cbae026481dbdf1862a25da7537f60b7d938038a8310cf3b0cd207ca1d3672e6"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
