[package]
name = "soci-snapshotter"
version = "0.1.0"
publish = false
build = "../build.rs"
edition = "2021"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/awslabs/soci-snapshotter/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.8.0.tar.gz"
sha512 = "aeec6a71a6df0325cac05bc7f87a0ca1ba3145b4ad4cad7647c5159b36fd2f600577487584218a75e8aee820c9c826976c752e718295c94fca9272b6a2dff10a"
bundle-root-path = "soci-snapshotter-0.8.0/cmd"
bundle-output-path = "bundled-cmd.tar.gz"
bundle-modules = [ "go" ]

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.8.0.tar.gz"
sha512 = "aeec6a71a6df0325cac05bc7f87a0ca1ba3145b4ad4cad7647c5159b36fd2f600577487584218a75e8aee820c9c826976c752e718295c94fca9272b6a2dff10a"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
