[package]
name = "soci-snapshotter"
version = "0.1.0"
publish = false
build = "../build.rs"
edition = "2021"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/awslabs/soci-snapshotter/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.7.0.tar.gz"
sha512 = "91c07db47a971b0e32554457036ae4eb90850c076e6e7c3c99d590332dd24a805ca977a8092bf60cf72fb82b42e2fb22c29fdf96de801625e1d44a4c9431b9b9"
bundle-root-path = "soci-snapshotter-0.7.0/cmd"
bundle-output-path = "bundled-cmd.tar.gz"
bundle-modules = [ "go" ]

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.7.0.tar.gz"
sha512 = "91c07db47a971b0e32554457036ae4eb90850c076e6e7c3c99d590332dd24a805ca977a8092bf60cf72fb82b42e2fb22c29fdf96de801625e1d44a4c9431b9b9"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
