[package]
name = "os"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
source-groups = [
    "api",
    "aws-smithy-experimental",
    "bottlerocket-release",
    "metricdog",
    "parse-datetime",
    "pciclient",
    "ghostdog",
    "updater",
    "logdog",
    "models",
    "imdsclient",
    "retry-read",
    "shimpei",
    "driverdog",
    "cfsignal",
    "bloodhound",
    "xfscli",
]

[lib]
path = "../packages.rs"

[build-dependencies]
glibc = { path = "../glibc" }
