[package]
name = "libzstd"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/facebook/zstd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz"
sha512 = "54a578f2484da0520a6e9a24f501b9540a3fe3806785d6bc9db79fc095b7c142a7c121387c7eecd460ca71446603584ef1ba4d29a33ca90873338c9ffbd04f14"

[[package.metadata.build-package.external-files]]
url = "https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz.sig"
sha512 = "aea8d07589a7bf26d0dd1047ca1c3448f41203d2da21fcb730d169529f87bcab1a3651775a1d39e8de17f5a0863fbd598c8becb0fed5d3c8c3154916ee7d51d1"

[build-dependencies]
glibc = { path = "../glibc" }
