[package]
name = "bash"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/bash"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/bash/bash-5.2.37.tar.gz"
sha512 = "c07e2715cca7c3c8435fcb13aaf2968671f10f9e1fe5edd7c63d7e34fb821c159087b70386e17bdda723d8223057b53810e75eb249b03ebfc847147b06a8101f"

[build-dependencies]
glibc = { path = "../glibc" }
libncurses = { path = "../libncurses" }
readline = { path = "../readline" }
